### ISSUE TITLE
LUA error when killing players

### ISSUE THREAD

**Issue by Nixxen** [linman0x90/dgks_classic#2]
Happens from time to time when killing people in the Hillsbrad raids.

`Message: Interface\AddOns\dgks_classic\dgks_classic.lua:1656: attempt to call global 'IsActiveBattlefieldArena' (a nil value)
Time: Fri Nov 15 01:44:29 2019
Count: 13`

**Comment by Nixxen** [comment]
Removing "and not IsActiveBattlefieldArena()" from the 3 relevant places in the lua fixes this.
It's not an API call in classic since there's no arenas yet.

**Comment by Nixxen** [comment]
Just a reminder. This issue is still there.
I completely forgot about it, but after the latest patch it started popping up again.

**Comment by linman0x90** [comment]
I see I will fix this today. Sorry for the slow response.

**Comment by linman0x90** [comment]
This was fixed along time ago.
